apiVersion: v1
kind: Service
metadata:
  labels:
    app: signals-ws
  name: signals-ws-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: signals-ws
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signals-ws
  labels:
    app: signals-ws
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9102'
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: signals-ws
  template:
    metadata:
      labels:
        app: signals-ws
    spec:
      containers:
      - name: signals-ws
        image: gcr.io/casestudy/signals-ws
        ports:
        - containerPort: 80
